package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006A6A)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFCCE8E8)
val onPrimaryContainerLight = Color(0xFF002020)
val secondaryLight = Color(0xFF4A6362)
val onSecondaryLight = Color(0xFFffffff)
val secondaryContainerLight = Color(0xFFD7E5E4)
val onSecondaryContainerLight = Color(0xFF002020)
val tertiaryLight = Color(0xFF4B607C)
val onTertiaryLight = Color(0xFFffffff)
val tertiaryContainerLight = Color(0xFFD3E4FF)
val onTertiaryContainerLight = Color(0xFF001C38)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFffffff)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFCFDF6)
val onBackgroundLight = Color(0xFF191C1C)
val surfaceLight = Color(0xFFFCFDF6)
val onSurfaceLight = Color(0xFF191C1C)
val surfaceVariantLight = Color(0xFFF4FBF9)
val onSurfaceVariantLight = Color(0xFF3F4948)
val outlineLight = Color(0xFFBFC8C7)
val outlineVariantLight = Color(0xFFCDE5E3)

// Some dark theme equivalents to fallback
val primaryDark = Color(0xFF4DD9D9)
val onPrimaryDark = Color(0xFF003737)
val primaryContainerDark = Color(0xFF004F4F)
val onPrimaryContainerDark = Color(0xFF6FF7F7)
val secondaryDark = Color(0xFFB1CCCB)
val onSecondaryDark = Color(0xFF1C3534)
val secondaryContainerDark = Color(0xFF334B4A)
val onSecondaryContainerDark = Color(0xFFCDE8E7)
val backgroundDark = Color(0xFF0F1514)
val onBackgroundDark = Color(0xFFDFE4E3)
val surfaceDark = Color(0xFF0F1514)
val onSurfaceDark = Color(0xFFDFE4E3)
val surfaceVariantDark = Color(0xFF3F4948)
val onSurfaceVariantDark = Color(0xFFBEC9C8)
val outlineDark = Color(0xFF899392)
val outlineVariantDark = Color(0xFF3F4948)
